repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: cluster

  # A short description of the repository that will show up on GitHub
  👩🏿‍💻👨🏿‍💻👩🏾‍💻👨🏾‍💻👩🏽‍💻👨🏽‍💻👩🏼‍💻👨🏼‍💻👩🏻‍💻👨🏻‍💻CNCF Community Groups (formerly meetups)

  # A URL with more information about the repository
  homepage: https://community.cncf.io/

  # Collaborators: give specific users access to this repository.
  # This should be managed via CLOWarden, see https://github.com/cncf/people
