name: New Cloud Native Community Group (CNCG) request
description: Request to create a new Cloud Native Community group by city. 
title: "[Group Request] Create a new chapter"
body:
- id: group_name
  type: input
  attributes:
    label: Requested name for the new CNCG by city. If you recently had a deactivated chapter, please do not fill out this form, and reach out to community-groups@cncf.io.
    placeholder: e.g. Cloud Native San Francisco
  validations:
    required: true
- id: location
  type: input
  attributes:
    label: What country are you wanting to start your community group in?
    placeholder: e.g. United States
  validations:
    required: true
- id: organizer_1
  type: textarea
  attributes:
    label: Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited)
    placeholder: e.g. Audra Montenegro, CNCF, https://github.com/AudMonte01, https://www.linkedin.com/in/audramontenegro/, Audra Montenegro in CNCF Slack
  validations:
    required: false
- id: organizer_2
  type: input
  attributes:
    label: Organizer 2
    placeholder: e.g. If you have a co-organizer, please list the same details as you did for yourself
  validations:
    required: false
- id: organizer_3
  type: input
  attributes:
    label: Organizer 3
    placeholder: e.g. If you have a co-organizer, please list the same details as you did for yourself
  validations:
    required: false
- id: content
  type: textarea
  attributes:
    label: What type of content or specific technologies do you want to focus on? If you run another meetup, please link it here.
    placeholder: e.g. Kubernetes, Observability, other or all CNCF projects
  validations:
    required: false
- id: community_profile
  type: textarea
  attributes:
    label: You must have a profile on community.cncf.io asscoiated with the above-listed email address(es)
    placeholder: e.g. https://community.cncf.io/u/m8bqcv/#/about, 
  validations:
    required: false
- id: organizer_coc
  type: checkboxes
  attributes:
    label: Code of Conduct
    description: "The Code of Conduct helps create a safe space for everyone. We require
      that everyone agrees to it, including any and all futre speakers and future co-organizers."
    options:
      - label: I agree to follow the CNCF code of conduct [https://github.com/cncf/foundation/blob/main/code-of-conduct.md]
        required: true
- id: organizer_residency
  type: checkboxes
  attributes:
    label: Where organizers reside
    description: "All CNCG organizers must live in the area they are inquiring to host a chapter in. The above-mentioned city must be where you reside full time."
    options:
      - label: I confirm I am local to or leave near the city I am proposing a chapter for.
        required: true
- id: organizer_affiliation
  type: checkboxes
  attributes:
    label: Organizers companies/affiliations
    description: "Not all CNCG organizers can be from the same company."
    options:
      - label: You agree if there is more than one organizer now, or onboarded in the future, the majority comes from different companies
        required: true
- id: organizer_inclusivity
  type: checkboxes
  attributes:
    label: Inclusive
    description: "You agree to be inclusive of all people eager to learn about cloud native, no matter what level of expertise they are in their journey."
    options:
      - label: I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
        required: true
- id: organizer_neutrality
  type: checkboxes
  attributes:
    label: Vendor Neutral
    description: "CNCGs should have vendor-nuetral content for the main portion of your meetups (note: sponsors can have up to 15 minutes on stage to pitch a product or service)"
    options:
      - label: I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), (and my other organizers) agree that the main content of our meetups will remain vendor-nuetral
        required: true
- id: organizer_branding
  type: checkboxes
  attributes:
    label: Agree to use CNCG branding
    description: "In an effort to avoide trademark miss-use, and have unity within the CNCG program, you agree to use [CNCG branding](https://github.com/cncf/artwork/blob/main/examples/other.md#cloud-native-community-groups)."
    options:
      - label: I agree to use the CNCG logo in my chapter and social branding
        required: true
- id: organizer_bevy
  type: checkboxes
  attributes:
    label: Registration through Bevy
    description: "In order to properly support your chapter with benefits, registration for your meetups must be through Bevy, or the current CNCF community platform."
    options:
      - label: I agree to host free registration in Bevy
        required: true
- id: organizer_activity
  type: checkboxes
  attributes:
    label: Remain an active chapter
    description: "You agree to host a meetup, study group, or virtual event at least 1 time every 90 days (quarter). And if you foresee a delay, I will notify the CNCF team via community-groups@cncf.io"
    options:
      - label: I agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.
        required: true
- id: organizer_collaboration
  type: checkboxes
  attributes:
    label: Collaboration with other chapters
    description: "CNCF has the right to approve additional chapters in your area if you live in city of over 1 million people"
    options:
      - label: I acknowledge the CNCF right to approve additional chapters in my area based on this criteria
        required: true
- id: organizer_diversity
  type: checkboxes
  attributes:
    label: Aim to have a diverse representation of speakers in your meetups
    description: "Diversity means something different for each country. The commonality among all countries is to strive to promote women or non-male speakers."
    options:
      - label: Along with my co-organizers, we will do our best to currate diverse content throughout the year
        required: true
