name: New Chapter Organizer Request
description: Request to become or be removed as organizer from existing chapter
title: "[Organizer Request] Add or Remove Organizer Name"
body:
- type: markdown
  attributes:
    value: |
      If you are an inquiring co-organizer, at this point you should have already tried to contact the organizers of the existing chapter on community.cncf.io via the 'Contact Us' button within the chapter, and you have not yet received a response. OR you are a current organizer that is requesting to remove a co-organizer, and tag them here for transparency (a conversation should have already taken place with this person one on one).
- id: chapter
  type: input
  attributes:
    label: Name of chapter inquiring about
    placeholder: e.g. Cloud Native San Francisco
  validations:
    required: true
- id: organizer
  type: textarea
  attributes:
    label: Tell us about the organizer and why they should be added or removed from the above-mentioned chapter
    placeholder: e.g. Audra Montenegro is resigning her role as co-organizer due to lack of time to commit to the chapter
  validations:
    required: true
- id: organizer_2
  type: textarea
  attributes:
    label: Tell us another the organizer and why they should be added or removed from the above-mentioned chapter
    placeholder: e.g. I, Audra Montenegro would like to join as a co-organizer. I have xyz experience that would be an asset to the chapter
  validations:
    required: false
- id: organizer_coc
  type: checkboxes
  attributes:
    label: Code of Conduct
    description: "The Code of Conduct helps create a safe space for everyone. We require that everyone agrees to it."
    options:
      - label: I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)
        required: true
- id: organizer_residency
  type: checkboxes
  attributes:
    label: Where organizer resides
    description: "All new CNCG organizers must live in the area they are inquiring to host a chapter in. The above-mentioned location must be where you reside full time."
    options:
      - label: I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)
        required: false
- id: organizer_affiliation
  type: checkboxes
  attributes:
    label: Organizers companies/affiliations
    description: "Not all CNCG organizers can be from the same company."
    options:
      - label: I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)
        required: false
- id: organizer_inclusivity
  type: checkboxes
  attributes:
    label: Inclusive
    description: "You agree to be inclusive of all people eager to learn about cloud native, no matter what level of expertise they are at in their open source journey."
    options:
      - label: I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)
        required: false
- id: organizer_neutrality
  type: checkboxes
  attributes:
    label: Vendor Neutral
    description: "CNCGs should have vendor-nuetral content for the main portion of your meetups. Please note that [sponsors can have up to 15 minutes on stage](https://github.com/cncf/communitygroups/blob/main/best_practices.md#sponsorships)"
    options:
      - label: I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)
        required: false
- id: organizer_activity
  type: checkboxes
  attributes:
    label: Remain an active chapter
    description: "You understand and agree to host a meetup, study group, or virtual event [at least 1 time every 90 days (quarter)](https://github.com/cncf/communitygroups/blob/main/README.md#community-group-inactivity). And if you foresee a delay, you will notify the CNCF team via community-groups@cncf.io"
    options:
      - label: I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)
        required: false
- id: organizer_collaboration
  type: checkboxes
  attributes:
    label: Collaboration with other chapters
    description: "CNCF has the right to approve additional chapters in your location if you live in a significant populous area."
    options:
      - label: I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)
        required: false
- id: organizer_diversity
  type: checkboxes
  attributes:
    label: Aim to have a diverse representation of speakers in your meetups
    description: "Diversity means something different for each country. The commonality among all countries is to strive to promote women or non-male speakers."
    options:
      - label: I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)
        required: false
- type: markdown
  attributes:
    value: |
      Please give CNCF up to 30 days to review your request.
