name: Check Nearby Chapters

on:
  issues:
    types: [opened]

jobs:
  check-nearby-chapters:
    # Only run if the issue title contains "[Group Request]"
    if: contains(github.event.issue.title, '[Group Request]')
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install axios cheerio

      - name: Check for nearby chapters
        id: check-chapters
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          node .github/workflows/scripts/check-nearby-chapters.js

      - name: Post comment with nearby chapters
        if: steps.check-chapters.outputs.nearby_chapters != ''
        uses: actions/github-script@v7
        with:
          script: |
            const nearbyChapters = process.env.NEARBY_CHAPTERS;
            const location = process.env.REQUESTED_LOCATION;

            const comment = `## 📍 Nearby Chapters Found

Thanks for your interest in creating a new CNCF Community Group chapter!

We found existing chapters near **${location}**:

${nearbyChapters}

**Next Steps:**
- Please review the chapters listed above to confirm there isn't overlap with your proposed location
- If you believe your location is sufficiently different or serves a distinct community, please comment below explaining the difference
- Consider reaching out to nearby chapter organizers to collaborate or understand their reach

If you have any questions, please reach out to community-groups@cncf.io`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
        env:
          NEARBY_CHAPTERS: ${{ steps.check-chapters.outputs.nearby_chapters }}
          REQUESTED_LOCATION: ${{ steps.check-chapters.outputs.requested_location }}
