name: Check for Nearby Chapters

on:
  issues:
    types: [opened]

jobs:
  check-nearby-chapters:
    name: Check for nearby chapters
    if: contains(github.event.issue.title, '[Group Request]')
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests geopy

      - name: Check for nearby chapters
        id: check
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          python .github/workflows/scripts/check_nearby_chapters.py

      - name: Comment on issue
        if: steps.check.outputs.nearby_chapters != ''
        uses: actions/github-script@v7
        with:
          script: |
            const nearbyChapters = process.env.NEARBY_CHAPTERS;
            const comment = `## ⚠️ Nearby Chapters Detected\n\nWe found existing CNCF Community Group chapters near your requested location:\n\n${nearbyChapters}\n\nPlease review these existing chapters:\n- Consider joining and collaborating with these existing organizers\n- If your location is sufficiently different or serves a distinct community, please provide additional context in this issue\n- Check the [CNCF Community Groups map](https://community.cncf.io/chapters/) for more details\n\nThe CNCF team will review your request and these nearby chapters during the evaluation process.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
        env:
          NEARBY_CHAPTERS: ${{ steps.check.outputs.nearby_chapters }}
