name: Check for Nearby Chapters

on:
  issues:
    types: [opened]

jobs:
  check-nearby-chapters:
    if: contains(github.event.issue.title, '[Group Request]')
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests geopy beautifulsoup4

      - name: Check for nearby chapters
        id: check-chapters
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          python .github/workflows/scripts/check_nearby_chapters.py

      - name: Comment on issue
        if: steps.check-chapters.outputs.nearby_chapters != ''
        uses: actions/github-script@v7
        with:
          script: |
            const nearbyChapters = process.env.NEARBY_CHAPTERS;
            const comment = `## ⚠️ Nearby Chapters Detected\n\n` +
              `We found existing CNCF Community Group chapters near your requested location:\n\n` +
              nearbyChapters + `\n\n` +
              `Please review these existing chapters. If they are in your area, we recommend:\n` +
              `- Reaching out to the current organizers to collaborate\n` +
              `- Filing an [organizer request](https://github.com/cncf/communitygroups/issues/new?assignees=&labels=&projects=&template=organizer-request.yml&title=%5BOrganizer+Request%5D+Add+or+Remove+Organizer+Name) to join as a co-organizer\n\n` +
              `If these chapters are not in your immediate area and you believe there is sufficient population to support a new chapter, please provide additional context in this issue.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
        env:
          NEARBY_CHAPTERS: ${{ steps.check-chapters.outputs.nearby_chapters }}
